import type { SkillDefinition } from './SkillRegistry.js'

export type SkillTrustLevel = 'official' | 'ecosystem'
export type WorkflowSkillReadinessTier = 'required' | 'recommended' | 'optional'

export interface WorkflowSkillCatalogEntry {
  id: string
  name: string
  description: string
  source: string
  installCommand: string
  trust: SkillTrustLevel
  readiness?: WorkflowSkillReadinessTier
  definition: SkillDefinition
}

export const WORKFLOW_AGENT_SKILL_CATALOG: WorkflowSkillCatalogEntry[] = [
  {
    id: 'impeccable',
    name: 'Impeccable',
    description: 'Deterministic UI anti-pattern detection and design refinement workflow for AI-generated interfaces.',
    source: 'https://github.com/pbakaus/impeccable',
    installCommand: 'npx -y impeccable skills install --yes',
    trust: 'ecosystem',
    readiness: 'required',
    definition: {
      id: 'impeccable',
      name: 'Impeccable',
      description: 'Deterministic UI anti-pattern detection and design refinement workflow',
      domain: 'planning',
      triggers: [
        { type: 'taskType', value: ['ui-design', 'frontend', 'visual-polish'], weight: 1.0 },
        { type: 'keyword', value: ['impeccable', 'design audit', 'ui polish', 'visual polish', 'component', 'layout', 'typography'], weight: 1.0 },
        { type: 'keyword', value: ['frontend', 'ui', 'ux', 'visual', 'responsive'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/impeccable/SKILL.md' } },
      priority: 98,
      installed: false,
      source: 'https://github.com/pbakaus/impeccable',
    },
  },
  {
    id: 'taste-skill',
    name: 'Taste Skill',
    description: 'Design-language generation workflow for selecting aesthetic direction before UI implementation.',
    source: 'https://github.com/LeonxlnX/taste-skill',
    installCommand: 'npx -y skills add LeonxlnX/taste-skill --yes',
    trust: 'ecosystem',
    readiness: 'recommended',
    definition: {
      id: 'taste-skill',
      name: 'Taste Skill',
      description: 'Design-language generation workflow for aesthetic direction and product tone',
      domain: 'planning',
      triggers: [
        { type: 'taskType', value: ['ui-design', 'landing-page', 'brand-site'], weight: 1.0 },
        { type: 'keyword', value: ['aesthetic', 'style', 'brand', 'landing', 'minimalist', 'brutalist', 'taste', 'redesign'], weight: 0.92 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/design-taste-frontend/SKILL.md' } },
      priority: 93,
      installed: false,
      source: 'https://github.com/LeonxlnX/taste-skill',
    },
  },
  {
    id: 'frontend-design',
    name: 'Frontend Design',
    description: 'Distinctive production-grade frontend UI design',
    source: 'https://github.com/anthropics/skills/tree/main/skills/frontend-design',
    installCommand: 'npx -y skills add anthropics/skills --skill frontend-design --yes',
    trust: 'official',
    readiness: 'recommended',
    definition: {
      id: 'frontend-design',
      name: 'Frontend Design',
      description: 'Distinctive production-grade frontend UI design',
      domain: 'planning',
      triggers: [
        { type: 'taskType', value: ['ui-design'], weight: 1.0 },
        { type: 'keyword', value: ['frontend', 'ui', 'ux', 'visual', 'responsive', 'component'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/frontend-design/SKILL.md' } },
      priority: 94,
      installed: true,
      source: 'https://github.com/anthropics/skills/tree/main/skills/frontend-design',
    },
  },
  {
    id: 'webapp-testing',
    name: 'Webapp Testing',
    description: 'Playwright-based local web application testing',
    source: 'https://github.com/anthropics/skills/tree/main/skills/webapp-testing',
    installCommand: 'npx -y skills add anthropics/skills --skill webapp-testing --yes',
    trust: 'official',
    readiness: 'required',
    definition: {
      id: 'webapp-testing',
      name: 'Webapp Testing',
      description: 'Playwright-based local web application testing',
      domain: 'verification',
      triggers: [
        { type: 'taskType', value: ['e2e-testing', 'ui-debugging'], weight: 1.0 },
        { type: 'phase', value: 'verify', weight: 0.8 },
        { type: 'keyword', value: ['playwright', 'browser', 'e2e', 'screenshot', 'console'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/webapp-testing/SKILL.md' } },
      priority: 92,
      installed: true,
      source: 'https://github.com/anthropics/skills/tree/main/skills/webapp-testing',
    },
  },
  {
    id: 'liteparse',
    name: 'LiteParse',
    description: 'Agent-first document parsing workflow for PDF, Office, image, OCR, screenshots, and batch ingestion.',
    source: 'https://github.com/run-llama/llamaparse-agent-skills',
    installCommand: 'npx -y skills add run-llama/llamaparse-agent-skills --skill liteparse --yes',
    trust: 'ecosystem',
    readiness: 'recommended',
    definition: {
      id: 'liteparse',
      name: 'LiteParse',
      description: 'Document parsing workflow with structured output, screenshots, batch mode, and OCR integration',
      domain: 'context',
      triggers: [
        { type: 'taskType', value: ['document-parsing', 'pdf-extraction', 'knowledge-ingestion'], weight: 1.0 },
        { type: 'keyword', value: ['pdf', 'parse', 'document', 'extract', 'ocr', 'liteparse', 'lit', 'pptx', 'docx', 'xlsx'], weight: 0.95 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/liteparse/SKILL.md' } },
      priority: 88,
      installed: false,
      source: 'https://github.com/run-llama/llamaparse-agent-skills',
    },
  },
  {
    id: 'storage-analyzer',
    name: 'Storage Analyzer',
    description: 'macOS and Windows disk usage analysis workflow with a guarded cleanup report.',
    source: 'https://github.com/KKKKhazix/khazix-skills/tree/main/storage-analyzer',
    installCommand: 'Bundled with scale-engine under .scale/skills/storage-analyzer',
    trust: 'ecosystem',
    readiness: 'recommended',
    definition: {
      id: 'storage-analyzer',
      name: 'Storage Analyzer',
      description: 'Read-only disk usage analysis and guarded storage cleanup report workflow',
      domain: 'context',
      triggers: [
        { type: 'taskType', value: ['storage-analysis', 'disk-cleanup', 'storage-cleanup'], weight: 1.0 },
        { type: 'keyword', value: ['storage analysis', 'disk cleanup', 'storage cleanup', 'disk full', 'drive full', 'c drive', 'C drive', '磁盘', '存储', '空间不够', '硬盘满了', 'C盘', '清理空间', '清缓存'], weight: 0.95 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '.scale/skills/storage-analyzer/SKILL.md' } },
      priority: 86,
      installed: true,
      source: 'https://github.com/KKKKhazix/khazix-skills/tree/main/storage-analyzer',
    },
  },
  {
    id: 'd2-diagram',
    name: 'D2 Diagram',
    description: 'Declarative diagram-as-code workflow for architecture, flow, and ER diagrams.',
    source: 'https://github.com/terrastruct/d2',
    installCommand: 'Install D2 from https://d2lang.com, then verify with d2 --version',
    trust: 'ecosystem',
    readiness: 'optional',
    definition: {
      id: 'd2-diagram',
      name: 'D2 Diagram',
      description: 'Declarative diagram-as-code workflow with validation, formatting, and sketch output',
      domain: 'planning',
      triggers: [
        { type: 'taskType', value: ['architecture-diagram', 'flow-chart', 'er-diagram'], weight: 1.0 },
        { type: 'keyword', value: ['diagram', 'flow', 'architecture', 'd2', 'sketch', 'visualize'], weight: 0.9 },
        { type: 'phase', value: 'plan', weight: 0.6 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/d2-diagram/SKILL.md' } },
      priority: 80,
      installed: false,
      source: 'https://github.com/terrastruct/d2',
    },
  },
  {
    id: 'opensquilla',
    name: 'OpenSquilla Harness',
    description: 'Optional agent harness reference for model routing, context loading, MetaSkill orchestration, and feedback loops.',
    source: 'https://github.com/opensquilla/opensquilla',
    installCommand: 'npx -y skills add opensquilla/opensquilla --yes',
    trust: 'ecosystem',
    readiness: 'optional',
    definition: {
      id: 'opensquilla',
      name: 'OpenSquilla Harness',
      description: 'Agent harness reference for routing, context management, orchestration, and self-evolution',
      domain: 'execution',
      triggers: [
        { type: 'taskType', value: ['agent-orchestration', 'multi-step-task', 'cost-optimization'], weight: 1.0 },
        { type: 'keyword', value: ['routing', 'harness', 'orchestrat', 'token', 'cost', 'agent', 'metaskill'], weight: 0.85 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/opensquilla/SKILL.md' } },
      priority: 75,
      installed: false,
      source: 'https://github.com/opensquilla/opensquilla',
    },
  },
  {
    id: 'code-reviewer',
    name: 'Code Reviewer',
    description: 'Critical, improvement, and nitpick review workflow',
    source: 'https://github.com/google-gemini/gemini-cli/tree/main/.gemini/skills/code-reviewer',
    installCommand: 'npx -y skills add https://github.com/google-gemini/gemini-cli --skill code-reviewer --yes',
    trust: 'official',
    readiness: 'required',
    definition: {
      id: 'code-reviewer',
      name: 'Code Reviewer',
      description: 'Critical, improvement, and nitpick review workflow',
      domain: 'verification',
      triggers: [
        { type: 'taskType', value: ['code-review'], weight: 1.0 },
        { type: 'phase', value: 'verify', weight: 0.7 },
        { type: 'keyword', value: ['review', 'critical', 'pull request', 'pr'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.gemini/skills/code-reviewer/SKILL.md' } },
      priority: 93,
      installed: true,
      source: 'https://github.com/google-gemini/gemini-cli/tree/main/.gemini/skills/code-reviewer',
    },
  },
  {
    id: 'fix',
    name: 'Fix',
    description: 'Format and lint repair before committing',
    source: 'https://github.com/facebook/react/tree/main/.claude/skills/fix',
    installCommand: 'npx -y skills add https://github.com/facebook/react --skill fix --yes',
    trust: 'official',
    readiness: 'recommended',
    definition: {
      id: 'fix',
      name: 'Fix',
      description: 'Format and lint repair before committing',
      domain: 'execution',
      triggers: [
        { type: 'taskType', value: ['lint-fix', 'bug-fix'], weight: 0.8 },
        { type: 'keyword', value: ['lint', 'format', 'prettier', 'eslint', 'ci'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/fix/SKILL.md' } },
      priority: 82,
      installed: true,
      source: 'https://github.com/facebook/react/tree/main/.claude/skills/fix',
    },
  },
  {
    id: 'pr-creator',
    name: 'PR Creator',
    description: 'Template-aware pull request creation workflow',
    source: 'https://github.com/google-gemini/gemini-cli/tree/main/.gemini/skills/pr-creator',
    installCommand: 'npx -y skills add https://github.com/google-gemini/gemini-cli --skill pr-creator --yes',
    trust: 'official',
    readiness: 'recommended',
    definition: {
      id: 'pr-creator',
      name: 'PR Creator',
      description: 'Template-aware pull request creation workflow',
      domain: 'deployment',
      triggers: [
        { type: 'taskType', value: ['pull-request', 'release'], weight: 1.0 },
        { type: 'keyword', value: ['pull request', 'pr', 'branch', 'merge'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.gemini/skills/pr-creator/SKILL.md' } },
      priority: 84,
      installed: true,
      source: 'https://github.com/google-gemini/gemini-cli/tree/main/.gemini/skills/pr-creator',
    },
  },
  {
    id: 'update-docs',
    name: 'Update Docs',
    description: 'Documentation impact analysis and update workflow',
    source: 'https://github.com/vercel/next.js/tree/canary/.claude/skills/update-docs',
    installCommand: 'npx -y skills add https://github.com/vercel/next.js --skill update-docs --yes',
    trust: 'official',
    readiness: 'recommended',
    definition: {
      id: 'update-docs',
      name: 'Update Docs',
      description: 'Documentation impact analysis and update workflow',
      domain: 'planning',
      triggers: [
        { type: 'taskType', value: ['docs-update'], weight: 1.0 },
        { type: 'keyword', value: ['docs', 'documentation', 'readme', 'api reference'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.claude/skills/update-docs/SKILL.md' } },
      priority: 82,
      installed: true,
      source: 'https://github.com/vercel/next.js/tree/canary/.claude/skills/update-docs',
    },
  },
  {
    id: 'find-skills',
    name: 'Find Skills',
    description: 'Discover installable skills for uncovered task capabilities',
    source: 'https://github.com/vercel-labs/skills/tree/main/skills/find-skills',
    installCommand: 'npx -y skills add https://github.com/vercel-labs/skills --skill find-skills --yes',
    trust: 'ecosystem',
    readiness: 'recommended',
    definition: {
      id: 'find-skills',
      name: 'Find Skills',
      description: 'Discover installable skills for uncovered task capabilities',
      domain: 'context',
      triggers: [
        { type: 'taskType', value: ['skill-discovery'], weight: 1.0 },
        { type: 'keyword', value: ['skill', 'capability', 'discover', 'install'], weight: 0.9 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/find-skills/SKILL.md' } },
      priority: 78,
      installed: true,
      source: 'https://github.com/vercel-labs/skills/tree/main/skills/find-skills',
    },
  },
  {
    id: 'fullstack-developer',
    name: 'Fullstack Developer',
    description: 'React, Node.js, database, and API prototyping workflow',
    source: 'https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/awesome_agent_skills/fullstack-developer',
    installCommand: 'npx -y skills add https://github.com/Shubhamsaboo/awesome-llm-apps --skill fullstack-developer --yes',
    trust: 'ecosystem',
    readiness: 'optional',
    definition: {
      id: 'fullstack-developer',
      name: 'Fullstack Developer',
      description: 'React, Node.js, database, and API prototyping workflow',
      domain: 'execution',
      triggers: [
        { type: 'taskType', value: ['fullstack-prototype'], weight: 1.0 },
        { type: 'keyword', value: ['react', 'next.js', 'node', 'api', 'database', 'prototype'], weight: 0.8 },
      ],
      execution: { type: 'skill-file', config: { skillPath: '~/.agents/skills/fullstack-developer/SKILL.md' } },
      priority: 70,
      installed: true,
      source: 'https://github.com/Shubhamsaboo/awesome-llm-apps/tree/main/awesome_agent_skills/fullstack-developer',
    },
  },
]

export function workflowAgentSkillDefinitions(): SkillDefinition[] {
  return WORKFLOW_AGENT_SKILL_CATALOG.map(entry => entry.definition)
}
