import type { EffectivenessMetric, WorkflowEffectivenessReport } from './WorkflowEffectiveness.js'

export function renderWorkflowEffectivenessReport(report: WorkflowEffectivenessReport): string {
  const fmtPct = (metric: EffectivenessMetric) => metric.value === null ? 'missing' : `${(Number(metric.value) * 100).toFixed(1)}%`
  const fmtNum = (metric: EffectivenessMetric) => metric.value === null ? 'missing' : String(metric.value)
  const fmtBool = (metric: EffectivenessMetric<boolean>) => metric.value === null ? 'missing' : metric.value ? 'yes' : 'no'
  return [
    'SCALE Workflow Effectiveness Report',
    `Project: ${report.projectDir}`,
    `Period: last ${report.lookbackDays} day(s)`,
    `Score: ${report.score === null ? 'unknown' : `${report.score}/100`} (${report.grade})`,
    '',
    'Delivery',
    `  First-pass verification: ${fmtPct(report.delivery.firstPassVerificationRate)}`,
    `  Average fix iterations: ${fmtNum(report.delivery.averageFixIterations)}`,
    `  Eval Pass@1: ${fmtPct(report.delivery.evalPassAt1Rate)}`,
    `  Eval Pass@3: ${fmtPct(report.delivery.evalPassAt3Rate)}`,
    `  Deployment frequency: ${fmtNum(report.delivery.deploymentFrequency)}`,
    `  Lead time for changes: ${fmtNum(report.delivery.leadTimeForChanges)}`,
    '',
    'Stability',
    `  Gate pass rate: ${fmtPct(report.stability.gatePassRate)}`,
    `  Gate fail rate: ${fmtPct(report.stability.gateFailRate)}`,
    `  Change failure proxy: ${fmtPct(report.stability.changeFailureProxy)}`,
    `  Restore time: ${fmtNum(report.stability.restoreTime)}`,
    `  Open failure replays: ${fmtNum(report.stability.openFailureReplays)}`,
    '',
    'Memory And Skills',
    `  Available memory providers: ${fmtNum(report.memory.availableProviders)}`,
    `  Default external provider available: ${fmtBool(report.memory.defaultExternalProviderAvailable)}`,
    `  Provider readiness: ${fmtPct(report.memory.providerReadinessRate)}`,
    `  Provider recall hit rate: ${fmtPct(report.memory.providerRecallHitRate)}`,
    `  Provider recall items: ${fmtNum(report.memory.providerRecallItems)}`,
    `  Provider context savings: ${fmtNum(report.memory.providerContextSavings)}`,
    `  Workflow skills installed: ${fmtPct(report.skills.installedWorkflowSkills)}`,
    `  Missing required skills: ${(report.skills.requiredMissingSkills.value ?? []).join(', ') || 'none'}`,
    `  Missing recommended skills: ${(report.skills.recommendedMissingSkills.value ?? []).join(', ') || 'none'}`,
    '',
    'Hallucination And Orchestration',
    `  Hallucinated fact failures: ${fmtNum(report.hallucination.evalHallucinatedFactFailures)}`,
    `  Human correction rate: ${fmtPct(report.hallucination.humanCorrectionRate)}`,
    `  Evidence-backed gate runs: ${fmtNum(report.hallucination.evidenceBackedGateRuns)}`,
    `  Instinct hit rate: ${fmtPct(report.orchestration.instinctHitRate)}`,
    `  Auto-fix success rate: ${fmtPct(report.orchestration.autoFixSuccessRate)}`,
    `  Gate escape proxy: ${fmtPct(report.orchestration.gateEscapeProxy)}`,
    '',
    'Agent Loop',
    `  Readiness: ${report.agentLoop.status} (${report.agentLoop.score}/100, report-only)`,
    `  Tool execution evidence: ${fmtBool(report.agentLoop.toolExecutionEvidence)}`,
    `  Loop recovery rate: ${fmtPct(report.agentLoop.loopRecoveryRate)}`,
    `  Guardrail coverage: ${fmtPct(report.agentLoop.guardrailCoverage)}`,
    `  Budget control evidence: ${fmtBool(report.agentLoop.budgetControlEvidence)}`,
    `  Handoff/delegation evidence: ${fmtBool(report.agentLoop.handoffOrDelegationEvidence)}`,
    `  Termination evidence: ${fmtBool(report.agentLoop.terminationEvidence)}`,
    '',
    `Measured signals: ${report.summary.measuredSignals}`,
    `Missing signals: ${report.summary.missingSignals}`,
    '',
    'Strengths',
    ...(report.summary.strengths.length ? report.summary.strengths.map(item => `  - ${item}`) : ['  - none measured yet']),
    '',
    'Gaps',
    ...(report.summary.gaps.length ? report.summary.gaps.map(item => `  - ${item}`) : ['  - none']),
    '',
    'Recommendations',
    ...(report.summary.recommendations.length ? report.summary.recommendations.map(item => `  - ${item}`) : ['  - keep collecting evidence']),
  ].join('\n')
}
